name: leaf
description: "Minimal Flutter state management with leafs, consumers, and reactive refs, and without boilerplate."
version: 0.0.2
homepage:
repository: https://github.com/leornt/leaf

environment:
  sdk: ^3.12.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
